//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kütüphane_modelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions
    {
        public int Id { get; set; }
        public System.DateTime deliveryDate { get; set; }
        public System.DateTime purchaseDate { get; set; }
        public bool isDelivery { get; set; }
        public long Members_tcID { get; set; }
        public int Books_bookNo { get; set; }
    
        public virtual Members Member { get; set; }
        public virtual Books Book { get; set; }
    }
}
